services:
  db:
    image: mysql:8.0
    container_name: simple-springboot-db-1
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: chat_app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: simple-springboot-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chat_app
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9012:9012"
    networks:
      - app-network
    volumes:
      - ./src/main/resources/templates:/app/src/main/resources/templates
      - ./src/main/resources/static:/app/src/main/resources/static

networks:
  app-network:
